<a href="https://colab.research.google.com/github/Ergys97/MLDM-Scripts/blob/main/Python-Introduction/03-Numpy-Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Practice - Hints - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [1]:
import numpy as np

## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [2]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [3]:
matrix = np.arange(9).reshape(3, 3)
np.fill_diagonal(matrix, 0)
print(matrix)

[[0 1 2]
 [3 0 5]
 [6 7 0]]


#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [4]:
matrix = np.ones((5, 5))
bordered_matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
print(bordered_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std, np.mean, np.std`

In [5]:
matrix = np.random.random((5, 5))
mean = np.mean(matrix)
std = np.std(matrix)
normalized_matrix = (matrix - mean) / std
print(normalized_matrix)

[[-1.25489521  0.02451912 -0.8642186   0.57275323  0.13639296]
 [-1.07334546 -1.34998348 -0.08917158  1.22960701 -0.35072692]
 [-1.61585629  0.42088387  0.89898887  0.84243866 -1.0104246 ]
 [ 1.50715473  1.58556932 -0.06850177 -0.26928323 -1.3142886 ]
 [ 0.36376961  1.33598569  0.34502446 -1.37239613  1.37000435]]


#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint: np.dot`

In [6]:
matrix1 = np.ones((5, 3))
matrix2 = np.ones((3, 2))
product = np.dot(matrix1, matrix2)
print(product)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [7]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

In [8]:
vector = np.random.uniform(-3, 12, 10)
sorted_vector = np.sort(vector)
print(sorted_vector)

[-0.19469875  0.29519243  0.5018604   0.81588619  7.78930344  7.84527001
  7.87937504  8.33373283 10.02109368 11.67331296]


#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

In [9]:
vector = np.random.random(10)
max_val = np.max(vector)
min_val = np.min(vector)
median_val = np.median(vector)
vector[np.argmax(vector)] = -max_val
vector[np.argmin(vector)] = median_val
print(vector)

[0.30518394 0.88416209 0.38801188 0.37223251 0.06971818 0.47434229
 0.71308777 0.29379512 0.40379125 0.15309246]


#### 9. Randomly replace p elements in a 2D nxn zero matrix to 1 (intermediate)
`hint: np.put, np.random.choice`

In [10]:
n = 5
p = 5

matrix = np.zeros((n, n))
indices = np.random.choice(np.arange(n*n), p, replace=False)
matrix[np.unravel_index(indices, (n, n))] = 1
print(matrix)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`

In [ ]:
matrix = np.random.random((5, 10))
mean_subtracted_matrix = matrix - matrix.mean(axis=1, keepdims=True)
print(mean_subtracted_matrix)